#! /bin/bash
#PROGRAM='ezwebframe_demos'
program=$1
programFile="$program.erl"
output=`eval 'erlc $programFile'`
if [ -z "$output" ]
then
    # printf "output:\n"
    erl -noshell -s $program start -s init stop
else
    printf "error:\n"
    printf "$output\n\n"
fi